param(
    [Parameter(Mandatory = $true)]
    [string]$ExamplesDir,

    [Parameter(Mandatory = $true)]
    [string]$Output
)

$ErrorActionPreference = "Stop"

function Escape-CppString {
    param([string]$Text)

    return $Text.Replace('\', '\\').Replace('"', '\"')
}

function Get-ExampleId {
    param([string]$Stem)

    $id = $Stem.ToLowerInvariant() -replace '[^a-z0-9]+', '_'
    $id = $id.Trim('_')
    if ([string]::IsNullOrWhiteSpace($id)) {
        $id = "example"
    }
    if ($id -notmatch '^[a-z_]') {
        $id = "example_$id"
    }
    return $id
}

function Get-DefaultTitle {
    param([string]$Stem)

    $words = ($Stem -replace '[-_]+', ' ').Trim()
    if ([string]::IsNullOrWhiteSpace($words)) {
        return "Example"
    }
    return $words
}

function Get-RawStringDelimiter {
    param(
        [string]$Content,
        [int]$Index
    )

    $suffix = 0
    while ($true) {
        $delimiter = "LC3_EXAMPLE_${Index}_${suffix}"
        if (-not $Content.Contains(")$delimiter`"")) {
            return $delimiter
        }
        $suffix += 1
    }
}

$examplesPath = [System.IO.Path]::GetFullPath($ExamplesDir)
$outputPath = [System.IO.Path]::GetFullPath($Output)
$outputDir = [System.IO.Path]::GetDirectoryName($outputPath)
[System.IO.Directory]::CreateDirectory($outputDir) | Out-Null

$files = Get-ChildItem -LiteralPath $examplesPath -Filter "*.asm" -File | Sort-Object Name
$usedIds = @{}
$entries = New-Object System.Collections.Generic.List[object]

foreach ($file in $files) {
    $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
    $content = $content -replace "`r`n", "`n"
    $content = $content -replace "`r", "`n"

    $title = $null
    $description = ""
    foreach ($line in ($content -split "`n")) {
        if ($line -match '^\s*;\s*name\s*:\s*(.+?)\s*$') {
            $title = $Matches[1]
        } elseif ($line -match '^\s*;\s*description\s*:\s*(.+?)\s*$') {
            $description = $Matches[1]
        }
    }

    if ([string]::IsNullOrWhiteSpace($title)) {
        $title = Get-DefaultTitle $file.BaseName
    }

    $baseId = Get-ExampleId $file.BaseName
    $id = $baseId
    $suffix = 2
    while ($usedIds.ContainsKey($id)) {
        $id = "${baseId}_${suffix}"
        $suffix += 1
    }
    $usedIds[$id] = $true

    $entries.Add([PSCustomObject]@{
        Id = $id
        Title = $title
        Description = $description
        Content = $content
    }) | Out-Null
}

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("// This file is generated by tools/embed_examples.ps1.")
[void]$builder.AppendLine("// Edit examples/*.asm instead of editing this file.")
[void]$builder.AppendLine()
[void]$builder.AppendLine('#include "src/embedded_examples.h"')
[void]$builder.AppendLine()
[void]$builder.AppendLine("#include <cstddef>")
[void]$builder.AppendLine()
[void]$builder.AppendLine("namespace embedded_examples {")

if ($entries.Count -gt 0) {
    [void]$builder.AppendLine("namespace {")
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("constexpr AssemblyExample kExamples[] = {")
    for ($i = 0; $i -lt $entries.Count; $i++) {
        $entry = $entries[$i]
        $delimiter = Get-RawStringDelimiter $entry.Content $i
        [void]$builder.AppendLine("    {")
        [void]$builder.AppendLine("        `"$(Escape-CppString $entry.Id)`",")
        [void]$builder.AppendLine("        `"$(Escape-CppString $entry.Title)`",")
        [void]$builder.AppendLine("        `"$(Escape-CppString $entry.Description)`",")
        [void]$builder.AppendLine("        R`"$delimiter($($entry.Content))$delimiter`"")
        [void]$builder.AppendLine("    },")
    }
    [void]$builder.AppendLine("};")
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("} // namespace")
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("const AssemblyExample* examples() {")
    [void]$builder.AppendLine("    return kExamples;")
    [void]$builder.AppendLine("}")
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("std::size_t exampleCount() {")
    [void]$builder.AppendLine("    return sizeof(kExamples) / sizeof(kExamples[0]);")
    [void]$builder.AppendLine("}")
} else {
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("const AssemblyExample* examples() {")
    [void]$builder.AppendLine("    return nullptr;")
    [void]$builder.AppendLine("}")
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("std::size_t exampleCount() {")
    [void]$builder.AppendLine("    return 0;")
    [void]$builder.AppendLine("}")
}

[void]$builder.AppendLine()
[void]$builder.AppendLine("const AssemblyExample* exampleAt(std::size_t index) {")
[void]$builder.AppendLine("    return index < exampleCount() ? examples() + index : nullptr;")
[void]$builder.AppendLine("}")
[void]$builder.AppendLine()
[void]$builder.AppendLine("const AssemblyExample* findExample(const std::string& id) {")
[void]$builder.AppendLine("    for (std::size_t i = 0; i < exampleCount(); i++) {")
[void]$builder.AppendLine("        const AssemblyExample* example = exampleAt(i);")
[void]$builder.AppendLine("        if (example && id == example->id) {")
[void]$builder.AppendLine("            return example;")
[void]$builder.AppendLine("        }")
[void]$builder.AppendLine("    }")
[void]$builder.AppendLine("    return nullptr;")
[void]$builder.AppendLine("}")
[void]$builder.AppendLine()
[void]$builder.AppendLine("} // namespace embedded_examples")

$newContent = $builder.ToString()
if ([System.IO.File]::Exists($outputPath)) {
    $oldContent = [System.IO.File]::ReadAllText($outputPath, [System.Text.Encoding]::UTF8)
    if ($oldContent -eq $newContent) {
        exit 0
    }
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $newContent, $utf8NoBom)
